trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-18.04'
    macOS:
      imageName: 'macos-10.14'
    Windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile"
    yarn && yarn compile
    echo ">>> Run tests"
    yarn test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'

- bash: |
    if echo "$SOURCE_BRANCH" | grep -E '^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$' ; then
      echo ">>> Publish"
      yarn deploy -p $PERSONAL_ACCESS_TOKEN
    else
      echo ">>> The tag format is invalid so skip the publish for the tag '$SOURCE_BRANCH'"
    fi
  displayName: Publish
  condition: |
    and(succeeded(),
      startsWith(variables['Build.SourceBranch'], 'refs/tags/'),
      eq(variables['Agent.OS'], 'Linux'))
  env:
    SOURCE_BRANCH: $(Build.SourceBranch)
